---
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "C"
exclude_patterns:
- "*.egg-info/"
- .cache/
- __pycache__/
- dist/
- htmlcov/
- tests/
