# Config file for automatic testing at travis-ci.org

env:
  global:
    - CC_TEST_REPORTER_ID=fc447195f19e98b977d2e7d2332d15528c51e91473505e61b9eb1cc402dd676a

sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
matrix:
  include:
    - python: "3.6"
      env: TOXENV=coverage
    - python: "3.6"
      env: TOXENV=flake8

install:
  - pip install tox-travis

before_script:
  - if [ "$TOXENV" = "coverage" ]; then
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
    fi
  - if [ "$TOXENV" = "coverage" ]; then
      chmod +x ./cc-test-reporter;
    fi
  - if [ "$TOXENV" = "coverage" ]; then
      ./cc-test-reporter before-build;
    fi

script:
  - tox -v

after_script:
  - if [ "$TOXENV" = "coverage" ]; then
      ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT;
    fi

before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
