name: Close inactive issues
on:
  schedule:
    - cron: "30 1 * * *" # in UTC

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions: {}

jobs:
  close-issues:
    name: Close inactive issues
    runs-on: ubuntu-latest
    permissions:
      issues: write # needed to label and close stale issues
      pull-requests: write # needed if PR staleness is re-enabled
    steps:
      - uses: actions/stale@b5d41d4e1d5dceea10e7104786b73624c18a190f # v10.2.0
        with:
          days-before-issue-stale: 90
          days-before-issue-close: 30
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale because it has been open for 90 days with no activity."
          close-issue-message: "This issue was closed because it has been inactive for 30 days since being marked as stale."
          # disable behavior on pull requests for now
          days-before-pr-stale: -1
          days-before-pr-close: -1
